language: go

notifications:
  email: false

branches:
  only:
    - master
    - develop
    - /^release-.*$/
    - new-test-system

services:
  - redis

env:
  - GOPATH="$TRAVIS_BUILD_DIR/gocode"

addons:
  apt:
    packages:
      - jq

before_install:
  - mysql -e "CREATE database IF NOT EXISTS pomodoros_dev;" -uroot
  - mkdir -p ./gocode/src ./gocode/bin ./gocode/pkg

install:
  - wget https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.26.zip -nv
  - unzip -q go_appengine_sdk_linux_amd64-1.9.26.zip
  - ./install-go-deps.sh

script:
  # start up the dev server and create DB tables
  - ./go_appengine/goapp serve api/ > goapp.out &
  - sleep 6
  - curl http://localhost:8080/auth/createtables
  # Test the API
  - cd test/api 
  - ./run.sh
  - cat goapp.out

# Testing the UI needs a browser ? some posts on selenium
