application: blue-pomodoros
module: api
version: 1
runtime: go
api_version: go1

handlers:
- url: /assets
  static_dir: www/assets

- url: /src
  static_dir: www/src

- url: /bower_components
  static_dir: www/bower_components

- url: /.*
  script: _go_app
  
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^bower_components$
